sudo: required
dist: trusty
language: node_js

node_js:
    #LTS version
    - "8.0"

cache:
    yarn: true
    directories:
        - node_modules

install:
    - yarn install

before_script:
    - export CI=false

deploy:
    skip_cleanup: true
    provider: script
    script: yarn build
    on:
        branch: ["master"]
